version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: iassetplatform/identity-service:latest
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    mem_limit: 1000m
    ports:
      - "9096:9096"
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: iassetplatform/business-process-service:latest
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx2560m -Xms150m
    mem_limit: 3000m
    ports:
      - "8085:8085"
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalogue-service:
    image: iassetplatform/catalogue-service-micro:latest
    ports:
      - "10095:8095"
    environment:
      - _JAVA_OPTIONS=-Xmx2560m -Xms150m
    mem_limit: 3000m
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    networks:
      - infra

  ##############################
  ####### Indexing Service #####
  ##############################

  indexing-service:
    image: iassetplatform/indexing-service:latest
    ports:
      - "9101:8080"
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
    mem_limit: 2000m
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: iassetplatform/frontend-service:fmp
    ports:
      - "8081:8080"
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 1000m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar
  
  frontend-service-sidecar:
    image: iassetplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    networks:
      - infra

  ###############################
  #### Data Channel Service #####
  ###############################

  data-channel-service:
    image: iassetplatform/data-channel-service:latest
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    ports:
      - "9099:9099"
    networks:
      - infra

  ###############################
  ## Data Aggregation Service ###
  ###############################

  data-aggregation-service:
    image: iassetplatform/data-aggregation-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx1024m -Xms150m
    mem_limit: 2000m
    networks:
      - infra

  ###############################
  ######## Trust Service ########
  ###############################

  trust-service:
    image: iassetplatform/trust-service:latest
    restart: always
    env_file:
      - env_vars
      - env_vars-prod
      - platform-config
    environment:
      PORT: 9098
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    mem_limit: 800m
    ports:
      - "9098:9098"
    networks:
      - infra

networks:
  infra:
    external:
      name: iasset-prod_default
